"""Build Hypercycle — concatenates Hyperkit + app-local CSS and emits per-module
JS <script> blocks into the inline HTML shell.

Follows the same Hyperkit integration pattern as Hyperline and Hyperagent:
- Hyperkit CSS loads first (tokens, keyframes, primitives, globals) for cascade order
- Hyperkit JS modules load first so app code can reference them
- App-local CSS and JS load after, overriding where needed
- Missing Hyperkit files fail loudly

Usage: python build.py
Output: Updates the HTML variable in generated_html.py
"""
import glob
from pathlib import Path

ROOT = Path(__file__).parent
HYPERKIT_DIR = ROOT.parent / ".hyperkit"
HYPERKIT_CSS_DIR = HYPERKIT_DIR / "css"
HYPERKIT_JS_DIR = HYPERKIT_DIR / "js"

# Hypercycle needs tooltips and toasts from Hyperkit; no greeting or cursor-trail.
HYPERKIT_JS_MODULES = ["utils.js", "toast.js"]

# Cascade order matters — tokens must land before anything that consumes them.
HYPERKIT_CSS_ORDER = (
    "tokens.css",
    "keyframes.css",
    "primitives.css",
    "globals.css",
    "components.css",
    "accessibility.css",
)


def concat_files(pattern):
    files = sorted(glob.glob(str(ROOT / pattern)))
    return "\n".join(Path(f).read_text(encoding="utf-8") for f in files)


def concat_hyperkit_css():
    """Read Hyperkit's shared CSS modules in cascade order. Fails loudly if missing."""
    parts = []
    for name in HYPERKIT_CSS_ORDER:
        f = HYPERKIT_CSS_DIR / name
        if not f.exists():
            raise FileNotFoundError(
                f"Hyperkit CSS file missing: {f}\n"
                "Hypercycle's build.py requires the shared CSS modules in "
                "../.hyperkit/css/. Restore the .hyperkit/ directory."
            )
        parts.append(f.read_text(encoding="utf-8"))
    return "\n".join(parts)


def render_hyperkit_js_blocks():
    """Emit one <script> block per Hyperkit JS module, in load order."""
    if not HYPERKIT_JS_DIR.exists():
        raise FileNotFoundError(
            f"Hyperkit JS directory missing: {HYPERKIT_JS_DIR}\n"
            "Hypercycle's build.py requires ../.hyperkit/js/."
        )
    blocks = []
    for name in HYPERKIT_JS_MODULES:
        f = HYPERKIT_JS_DIR / name
        if not f.exists():
            raise FileNotFoundError(
                f"Hyperkit JS module missing: {f}\n"
                f"Hypercycle's build.py expects {HYPERKIT_JS_MODULES} "
                "in ../.hyperkit/js/."
            )
        content = f.read_text(encoding="utf-8")
        blocks.append(f"<!-- hyperkit/{name} -->\n<script>\n{content}\n</script>")
    return "\n".join(blocks)


def render_js_blocks():
    """Emit one <script> block per app-local JS module."""
    files = sorted(glob.glob(str(ROOT / "assets/js/*.js")))
    blocks = []
    for f in files:
        content = Path(f).read_text(encoding="utf-8")
        blocks.append(f"<!-- {Path(f).name} -->\n<script>\n{content}\n</script>")
    return "\n".join(blocks)


def build():
    css = concat_hyperkit_css() + "\n" + concat_files("assets/css/*.css")
    js_blocks = render_hyperkit_js_blocks() + "\n" + render_js_blocks()

    shell_path = ROOT / "assets" / "shell.html"
    if not shell_path.exists():
        raise FileNotFoundError(f"Shell template missing: {shell_path}")
    shell = shell_path.read_text(encoding="utf-8")

    for token in ("{{CSS}}", "{{JS_BLOCKS}}"):
        if token not in shell:
            raise ValueError(f"Shell template is missing the {token} placeholder")

    html = shell.replace("{{CSS}}", css).replace("{{JS_BLOCKS}}", js_blocks)

    out = ROOT / "generated_html.py"
    out.write_text(
        f'"""Auto-generated by build.py — do not edit."""\n\nHTML = {repr(html)}\n',
        encoding="utf-8",
    )

    js_count = len(sorted(glob.glob(str(ROOT / "assets/js/*.js"))))
    print(f"Built: {len(css)} bytes CSS, {js_count} local JS modules -> generated_html.py")


if __name__ == "__main__":
    build()
